# ===================================================================
# Spring Boot configuration for the "heroku" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    instance:
        hostname: brainappbackend.herokuapp.com
        non-secure-port: 80
        prefer-ip-address: false
    client:
        service-url:
            defaultZone: ${JHIPSTER_REGISTRY_URL}/eureka/

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${JDBC_DATABASE_URL}
        username: ${JDBC_DATABASE_USERNAME}
        password: ${JDBC_DATABASE_PASSWORD}
        hikari:
            maximumPoolSize: 8
playoff:
    client:
        domain: playoff.cc
        id: ZTFiNjJmYmItOTljOS00ZGU2LWJhNjctZTZkMTk5NDZhZWUz
        secret: ZWMyMDU1NDgtZTE3OC00MzE2LTg0N2UtN2JjMjE2NTZlN2UyNmZjMzJmYzAtYzg0OS0xMWU3LWE2MjMtODU5YjhjNzcwNTMx
validationBypass: officinapower
