version: '2'
services:
    brainappbackend-app:
        image: brainappbackend
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://brainappbackend-postgresql:5432/brainappbackend
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    brainappbackend-postgresql:
        extends:
            file: postgresql.yml
            service: brainappbackend-postgresql
