version: '2'
services:
    gatoradeapp:
        image: gatorade
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gatorade-postgresql:5432/Gatorade
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gatorade-postgresql:
        extends:
            file: postgresql.yml
            service: gatorade-postgresql
